[tool.black]
line-length = 79
target-version = ['py38']
include-trailing-comma = true
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | node_modules
  | lib
)/
'''

[tool.isort]
py_version = '38'
line_length = 79
force_grid_wrap = 0
combine_as_imports = true
skip = []
multi_line_output = 3
include_trailing_comma = true
lines_after_imports = 2
use_parentheses = true
ensure_newline_before_comments = true
known_first_party = []
known_third_party = []
